### ISSUE TITLE
Snowflake Data Connectors (SnowPark)  

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-plugins#108]
## Description
I think there's scope to create a series of data connectors that would allow Kedro users to connect to Snowflake in different ways. This usage pattern was identified in the kedro-org/kedro#1653 research, that sometimes our users want to leverage SQL-based workflows for their data engineering pipelines. These connectors essentially simplify use of Python when you need it for the data science part of your workflow.  

While I have created this issue, I think it's important to document why we have seen users create Snowflake datasets and not leverage our `pandas.SQLTableDataSet` and `pandas.SQLQueryDataSet` to do the same, especially in the case of workflows based on Pandas. 

## Possible Implementation

This tasks proposes building out the following data connectors: 

- `spark.SnowflakeTableDataSet` - Load and saves data from/to a table as a Spark DataFrame.
- `spark.SnowflakeQueryDataSet` - Executes a SQL query on save(), can either load the table as a Spark DataFrame
- `pandas.SnowflakeTableDataSet` - Load and saves data from/to a table as a Pandas DataFrame.
- `pandas.SnowflakeQueryDataSet` - Executes a SQL query on save(), can either load the table as a Spark DataFrame

**Comment by merelcht** [comment]
A Snowpark dataset was added in https://github.com/kedro-org/kedro-plugins/pull/104 and released in `kedro-datasets` 1.1.0.
