### ISSUE TITLE
Telemetry breaks everything if there's no write permissions

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro-plugins#11]
## Description
As seen on databricks repos, which currently do not have write access, running any kedro command in a directory with no write access will raise an error with kedro-telemetry which then stops kedro from running everything.

This isn't the first time that an exception raised by kedro-telemetry has stopped kedro commands from working rather than just raising a warning and carrying on. I wonder if we should wrap the whole plugin in a `try/except` to catch any exceptions we don't anticipate. A broken kedro-telemetry shouldn't prevent users from using kedro.

## Steps to reproduce
1. Go to https://gitpod.io/#https://github.com/kedro-org/kedro
2. `pip install kedro-telemetry`
3. `chmod a=rx /workspace/project`
4. `kedro info`

This will give the following exception and not execute the kedro command at all:
```
PermissionError: [Errno 13] Permission denied: '/workspace/project/.telemetry'
```

**Comment by MerelTheisenQB** [comment]
"A broken kedro-telemetry shouldn't prevent users from using kedro." -> No error in `kedro-telemetry` should prevent a user from running Kedro, so as part of this fix ensure that other errors won't break Kedro either.
