### ISSUE TITLE
Adding Polars' dataframe as a dataset

### ISSUE THREAD

**Issue by lhegstrom** [kedro-org/kedro-plugins#110]
## Description

[Polars is a dataframe library written in Rust with a python API that is gaining a lot of traction.](https://www.pola.rs/) It has ~13k stars on github, and numerous blog posts are appearing on its performance.

## Context

It certainly feels like it's only a matter of time before this library becomes one of the "standard" data analysis tools - like dask, spark, and others have become. Having an out of the box implementation in Kedro would allow organizations that are beginning to implement this library to have a clean switch without having to implement a custom, AbstractDataSet.

## Possible Implementation
Reading, and writing CSVs, parquet and others in Polars [seems relatively straight forward.](https://pola-rs.github.io/polars/py-polars/html/reference/io.html) One concern would be transcoding between pandas -> Polars, or Polars to Pandas, polar to dask, etc. may require a little more thought as [Polars does not use an index.](https://pola-rs.github.io/polars-book/user-guide/coming_from_pandas.html)

**Comment by astrojuanlu** [comment]
Thanks for the suggestion @lhegstrom! I'm a big fan of Polars. Would you like to try contributing this? Otherwise I'll be happy to take care of it myself.

**Comment by lhegstrom** [comment]
@astrojuanlu I'd be happy to take a stab at implementing this. I probably won't be able to do much before the weekend, ut will follow-up

**Comment by astrojuanlu** [comment]
Sorry @lhegstrom, didn't realize there's https://github.com/kedro-org/kedro-plugins/pull/95 already!

**Comment by astrojuanlu** [comment]
xref https://github.com/kedro-org/kedro-plugins/pull/116

**Comment by astrojuanlu** [comment]
Current effort is in gh-170
