### ISSUE TITLE
Performance profiling on `kedro new` with starter and without starter

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-plugins#120]
When the telemetry is enabled and the Internet connection is choppy or poor, `kedro new` takes a lot to run. 

It could be because of the telemetry timeout:

https://github.com/kedro-org/kedro-plugins/blob/7fc511f2013002d2d85b89014f49384f735e6f76/kedro-telemetry/kedro_telemetry/plugin.py#L204

Or it could be because of cloning the starter itself. This is related to https://github.com/kedro-org/kedro/issues/1476

**Comment by astrojuanlu** [comment]
Example from yours truly:

```
% /usr/bin/time -p kedro new --starter=standalone-datacatalog --config=kedro.yaml

The project name 'kedro-polars' has been applied to: 
- The project title in /Users/juan_cano/Projects/QuantumBlack Labs/talk-kedro-polars/kedro-polars/README.md 
- The folder created for your project in /Users/juan_cano/Projects/QuantumBlack Labs/talk-kedro-polars/kedro-polars 
- The project's python package in /Users/juan_cano/Projects/QuantumBlack Labs/talk-kedro-polars/kedro-polars/src/kedro_polars

A best-practice setup includes initialising git and creating a virtual environment before running 'pip install -r src/requirements.txt' to install project-specific dependencies. Refer to the Kedro documentation: https://kedro.readthedocs.io/

Change directory to the project generated in /Users/juan_cano/Projects/QuantumBlack Labs/talk-kedro-polars/kedro-polars by entering 'cd /Users/juan_cano/Projects/QuantumBlack Labs/talk-kedro-polars/kedro-polars'
real 24.91
user 1.43
sys 1.03
```

(almost 25 seconds for a `kedro new`)

**Comment by ankatiyar** [comment]
Suggestion: Making `kedro-telemetry` use `after_command_run` hook instead of `before_command_run` might solve this problem!

**Comment by astrojuanlu** [comment]
Thanks @ankatiyar! I think when I opened this issue I had the impression that this was because of telemetry, but actually it could be cloning the starter. I'm renaming this to clarify.

**Comment by merelcht** [comment]
Closing in favour of https://github.com/kedro-org/kedro/issues/1476
