### ISSUE TITLE
Add a `save` method for the `APIDataSet`

### ISSUE THREAD

**Issue by FlorianGD** [kedro-org/kedro-plugins#166]
## Description
We sometimes want to save some data with a REST Api (say with Django Rest Framework), most of the time issuing a POST request. So far, the `APIDataSet` is read only, with the `_save` method raising a `DataSetError`, we'd want to extend it to make a request.

## Context
I have successfully subclassed the `APIDataSet` to overwrite this method, but it could be useful to have this natively here.

## Possible Implementation
One option would be to use the same args as the `APIDataSet`, and to only define it as a saved dataset. One argument that I needed was a `chunk_size` which could be part of the `save_args` to limit the size of the payload when the data we try to save is too big and causes issues.
The data that we save is a list of dict, most of the time the result of a `pandas.DataFrame.to_dict(orient="records")`.

## Possible Alternatives
The accepted data could be a dataframe directly, but I feel like adding a node so that the users have to be explicit about their serialization would lead to less pain in the end ;).

We could hardcode the `POST` method, but I can image cases where a `PUT` method for a partial update could be useful as well.

cc @McDonnellJoseph

**Comment by astrojuanlu** [comment]
See pull request gh-180 🚀
