### ISSUE TITLE
Support parquet and feather datasets from GeoPandas

### ISSUE THREAD

**Issue by Calychas** [kedro-org/kedro-plugins#196]
## Description
Two datasets for feather and parquet formats based on GeoPandas, which will make loading and saving GeoDataFrames with geometries easier.

## Context
When operating on geospatial data GeoPandas is of great use, however at the moment kedro-datasets plugin only supports [GeoJsonDataset](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/geopandas/geojson_dataset.py). It is possible to load and save parquet and feather files with geometries using standard pandas' datasets, but the geometry data needs special treatment afterwards (e.g. parsing WKB and creating GeoDataFrame manually).

## Possible Implementation
Take an implementation of existing geopandas.GeoJsonDataset, then create geopandas.ParquetDataSet and geopandas.FeatherDataSet. I have an already working implementation privately and I can try to add it here

**Comment by noklam** [comment]
@Calychas Awesome, would you be able to create a PR?

**Comment by Calychas** [comment]
@noklam Yes, I will try to do that sometime in the following 2 weeks

**Comment by SajidAlamQB** [comment]
Awesome, thank you!

**Comment by noklam** [comment]
@Calychas Hey! pinning to see if you still have some bandwidth to add support for this :)

**Comment by Calychas** [comment]
Hey @noklam! Sorry for the delay, just came back to this task

**Comment by Calychas** [comment]
Which dataset would you consider a gold standard for implementation to base the new datasets on? When I look over some of the datasets sometimes I see some minor discrepancies - e.g. using BytesIO or not

**Comment by noklam** [comment]
@Calychas CDVDataSet is probably the most common one.
