### ISSUE TITLE
Bump IPython dependencies for starters following `kedro`

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-plugins#197]
## Description
Short description of the problem here.
Following on https://github.com/kedro-org/kedro/pull/2314, we should update the starter IPython version to the same as `kedro`.

## Context
How has this bug affected you? What were you trying to accomplish?
 [An user found conflicting version](https://kedro-org.slack.com/archives/C03RKP2LW64/p1682611387720839) between `kedro` and `kedro-starter` and was confused.
We should update the dependencies anyway since it's for a security patch in IPython, same reason as https://github.com/kedro-org/kedro/pull/2314.

## Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [And so on...]

## Expected Result
Tell us what should happen.

## Actual Result
Tell us what happens instead.

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`):
* Python version used (`python -V`):
* Operating system and version:

**Comment by merelcht** [comment]
Completed in https://github.com/kedro-org/kedro-starters/pull/128
