### ISSUE TITLE
Add `safetensors` dataset

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-plugins#221]
https://huggingface.co/blog/safetensors-security-audit

> 🐶[Safetensors](https://github.com/huggingface/safetensors) is a library for saving and loading tensors in the most common frameworks (including PyTorch, TensorFlow, JAX, PaddlePaddle, and NumPy).

```python
import torch
from safetensors.torch import load_file, save_file

weights = {"embeddings": torch.zeros((10, 100))}
save_file(weights, "model.safetensors")
weights2 = load_file("model.safetensors")
```

Comparison with other formats: https://github.com/huggingface/safetensors#yet-another-format-

> For Hugging Face, EleutherAI, and Stability AI, the master plan is to shift to using this format by default.

**Comment by MinuraPunchihewa** [comment]
Hey @astrojuanlu,
Can I give this a shot?
I had previously commented on this [issue](https://github.com/kedro-org/kedro-plugins/issues/163), but I am having trouble with my Hive setup and I would like to tackle it later.

**Comment by astrojuanlu** [comment]
Well, pressure is mounting to move away from `pickle` 😄 https://www.forbes.com/sites/iainmartin/2024/10/22/hackers-have-uploaded-thousands-of-malicious-models-to-ais-biggest-online-repository/

From @/adrinjalali [on LinkedIn](https://www.linkedin.com/posts/adrinjalali_hackers-have-uploaded-thousands-of-malicious-activity-7255132471581634560--Slc?utm_source=share&utm_medium=member_desktop)

> The core of the problem being `pickle` format. This is nothing new, and the community has been working quite hard to mitigate these issues for a while at this point. However, those pickle files are still there and people still load them.
>
> There are tools which you can use to avoid loading pickle files:
> - `safetensors`: https://docs.rs/safetensors/latest/safetensors/ for DL models
> - `skops.io`: https://skops.readthedocs.io/en/stable/persistence.html for statistical ML and scikit-learn based models (and most other python objects)
