### ISSUE TITLE
Support Polars lazy evaluation

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-plugins#224]
## Description
Polars is efficient and support lazy evaluation mode which could be useful for memory hungry pipeline.

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.scan_csv.html
Maybe supporting a flag with `lazy` to use `pl.scan_csv` ?

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by noklam** [comment]
I think it's different. Polars already support this out of the box, so there isn't much implementation overhead.  Something like this:
```python
if lazy:
  pl.scan_csv(xxx)
else:
  pl.read_csv(xxx)
```

**Comment by astrojuanlu** [comment]
The third one looks the most promising to me! Many things in Polars are experimental and the project evolves fast, but I think it's worth trying.

**Comment by noklam** [comment]
Why using fsspec contradict with lazy loading?

**Comment by MatthiasRoels** [comment]
> Why using fsspec contradict with lazy loading?

It does not contradict it per se. It’s just that when `fsspec`, you use Python for I/O which means that you loose all the `polars` specific I/O goodies (read Rust implementation). Hence, this will negatively impact performance. 

What happens under the hood is that Python code (from `fsspec`) is responsible for reading data in memory at which moment in time Rust (`polars`) takes over for the actual processing. This means that you can’t benefit from things like predicate pushdown etc.

**Comment by astrojuanlu** [comment]
IIUC, `pyarrow.dataset` https://arrow.apache.org/docs/python/dataset.html provides lazy/deferred reading capabilities in general, am I right?

Don't think Arrow would work for all datasets (think of weird stuff like Video, HDF5 and so on) but definitely worth giving it some thought for tabular datasets.

In any case, for a first iteration maybe we don't need to strive for consistency, and just focus on Polars lazy evaluation.
