### ISSUE TITLE
Support Delta Table with a non-spark implementation

### ISSUE THREAD

**Issue by everdark** [kedro-org/kedro-plugins#226]
## Description

In `kedro-datasets` 1.3.0 a [new dataset dedicated for Delta Table](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/spark/deltatable_dataset.py) has been added, which is based on `pyspark`. Is there any plan to also add support for a non-spark implementation for Delta Lake? If not, I myself with some other folks are happy to contribute. :)

## Context

Not all use cases depend on Spark but they may still need to interact with Delta Lake. It won't be suitable to add Spark as a dependency simply because we want to deal with Delta Tables.

## Possible Implementation

Create a custom dataset that is based on the official Delta Lake Python-binding: https://github.com/delta-io/delta-rs/tree/main/python

**Comment by noklam** [comment]
This is a reasonable request and PR is very welcomed! We have a ticket here for reading Delta via Pandas but the priority isn't high for now. We would prefer it is contributed by the community.

https://github.com/kedro-org/kedro-plugins/issues/159

**Comment by everdark** [comment]
Nice! Will work on this.

**Comment by merelcht** [comment]
Completed in https://github.com/kedro-org/kedro-plugins/issues/226
