### ISSUE TITLE
Provide more helpful message for `kedro airflow create -h`

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-plugins#244]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

![image](https://github.com/kedro-org/kedro-plugins/assets/18221871/4e76dad7-3a14-4fde-81d2-0f40334d7bc1)

The current CLI help message isn't very clear, we can probably reuse some of the message from `kedro` or just copy it over.
## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by ankatiyar** [comment]
I believe this has more or less been completed by @sbrugman. #233 
```
Usage: kedro airflow create [OPTIONS]

  Create an Airflow DAG for a project

Options:
  -p, --pipeline TEXT         Name of the registered pipeline to convert. If
                              not set, the '__default__' pipeline is used.
  -e, --env TEXT              Kedro configuration environment name. Defaults
                              to `local`.
  -t, --target-dir DIRECTORY  The directory path to store the generated
                              Airflow dags
  -j, --jinja-file FILE       The template file for the generated Airflow dags
  --params TEXT               Specify extra parameters that you want to pass
                              to the context initialiser. Items must be
                              separated by comma, keys - by colon or equals
                              sign, example: param1=value1,param2=value2. Each
                              parameter is split by the first comma, so
                              parameter values are allowed to contain colons,
                              parameter keys are not. To pass a nested
                              dictionary as parameter, separate keys by '.',
                              example: param_group.param1:value1.
  -h, --help                  Show this message and exit.
```

**Comment by astrojuanlu** [comment]
Further improvements always welcome of course :) Closing for now!
