### ISSUE TITLE
`kedro-airflow` not compatible with `kedro-viz`

### ISSUE THREAD

**Issue by sbrugman** [kedro-org/kedro-plugins#269]
## Description
```
The conflict is caused by:
    kedro-airflow 0.5.1 depends on semver~=2.10
    kedro-viz 6.3.3 depends on semver~=3.0
```

**Comment by deepyaman** [comment]
Pretty sure you can just relax the upper bound for `kedro-airflow`; let me also check if there's any reason for `kedro-viz` to have that restrictive lower bound.

**Comment by sbrugman** [comment]
Just tested, `kedro-airflow` works fine with `semver=3.0.1`
