### ISSUE TITLE
`kedro-airflow` convert all pipelines

### ISSUE THREAD

**Issue by sbrugman** [kedro-org/kedro-plugins#274]
## Description
In the current setup, one needs to write a script to convert all pipelines at once, e.g. 
```bash
kedro registry list  | grep '^-' | sed "s/^- //g" >> ./pipelines.txt
cat ./pipelines.txt | while read line;
do 
    kedro airflow create --pipeline "$line" --jinja-file ./resources/airflow/airflow_dag_template.py.j2 --target-dir dags/; 
done
rm ./pipelines.txt
```

It would be useful if `kedro-airflow` took care of this.

Are you open to a PR for this?

## Context
In practice we would like to have all pipelines available in Airflow in order to run them with different configurations, or on individual schedules. For instance, some pipelines are heavier than others and can be ran less often.

## Possible Implementation
We could add another parameter, e.g. `--all` that is exclusive with the `--pipeline` argument

## Possible Alternatives
Currently, the default argument is `__default__`.
We could choose to make the default argument `None`, and if left unspecified to convert all pipelines.

Alternatively, add a command that wraps the `kedro airflow create` command.
`kedro airflow create-all`

**Comment by astrojuanlu** [comment]
> We could add another parameter, e.g. `--all` that is exclusive with the `--pipeline` argument

Sounds good to me! @amandakys what do you think from a DX perspective?

**Comment by sbrugman** [comment]
I'll submit a PR
