### ISSUE TITLE
Support ParquetDataSet for polars

### ISSUE THREAD

**Issue by Sage0614** [kedro-org/kedro-plugins#284]
## Context
Parquet is popular storage format, and polars have native support for it, I would like see first class support for eager mode (polars.read_parquet/write_parquet) in the short term and lazy mode (polars.scan_parquent) in the long term

**Comment by astrojuanlu** [comment]
Hi @Sage0614 ! Could you please try https://github.com/kedro-org/kedro-plugins/pull/170 and let us know if it worked for your use case?

**Comment by Sage0614** [comment]
> Hi @Sage0614 ! Could you please try #170 and let us know if it worked for your use case?

That looks good to me, one thing to add is the jsonschema should also be updated to reflect the change in #170

https://github.com/kedro-org/kedro/tree/main/static/jsonschema
