### ISSUE TITLE
`kedro-airflow` builds are failing

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#295]
## Description
The `kedro-docker` build that's run every night has been failing for a while now.

## Context
This doesn't just seem to be a flaky build, so we should fix it to ensure the quality of the plugin.

## Steps to Reproduce
See builds: https://github.com/kedro-org/kedro-plugins/actions?query=event%3Aschedule

**Comment by ankatiyar** [comment]
It's failing with `ModuleNotFoundError: No module named 'pyspark'`. I suspect it might be the https://github.com/kedro-org/kedro-plugins/issues/290

**Comment by noklam** [comment]
![Image](https://github.com/kedro-org/kedro-plugins/assets/18221871/8b9c1fda-9931-4b8e-bc76-4f436d64a45e)

It seems like kedro-airflow build are failing now instead of kedro-docker

**Comment by ankatiyar** [comment]
Follow up issue - https://github.com/kedro-org/kedro-plugins/issues/315
