### ISSUE TITLE
Make `kedro-airflow` compatible with latest version of `apache-airflow`

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro-plugins#315]
## Description

With the release of `apache-airflow 2.7.0` the end to end tests for `kedro-airflow` started failing. 
As a temporary fix, we're pinning the version of `apache-airflow ` to `<2.7.0`(https://github.com/kedro-org/kedro-plugins/pull/314) in the test requirements but we should investigate if there's something that needs fixing on Kedro side to make it work.

**Comment by astrojuanlu** [comment]
https://github.com/apache/airflow/releases/tag/2.8.0
