### ISSUE TITLE
Incorrect(?) warning when using SparkDataSet on Databricks with S3

### ISSUE THREAD

**Issue by alamastor** [kedro-org/kedro-plugins#319]
## Description
Using a `SparkDataSet` on Databricks with a `filepath` that starts with `s3://` produces a warning; `Using SparkDataSet on Databricks without the `/dbfs/` prefix in the filepath is a known source of error.` The error comes from [here](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/spark/spark_dataset.py#L287). I don't think this is actually a problem.

## Context
The warning is not clear about why this is a problem, using `s3` doesn't seem to be a cause of error for my use case. It creates log messages which need to be filtered.

## Steps to Reproduce
1. Use a `SparkDataSet` on Databricks with a `filepath` that starts with `s3://`.

## Expected Result
The warning should be more clear about why this is a problem if it is actually a problem or should not be produced.

## Actual Result
Confusing warning produced.

## Your Environment
Occurs on current master when running on Databricks due to https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/spark/spark_dataset.py#L286C7-L286C7.

**Comment by astrojuanlu** [comment]
Thanks for the heads up @alamastor. @noklam I see this comes from https://github.com/kedro-org/kedro-plugins/issues/117#issuecomment-1470891953, do you want to add some more context?

**Comment by noklam** [comment]
I see what's the problem. The assumption here is we assume you are using `dbfs` on Databricks. Is there a reason why you are not using `dbfs` when you are using Databricks already?

I think in this case there is no problem and we shouldn't raise the warning. In databricks if you are not using `dbfs`, the data will be saved to the driver node, which creates weird bug( You may see the data on the notebook you created, but you get FileNotFound on other nodes). Under the hood, Databricks also have some [magic path conversion](https://docs.databricks.com/en/files/index.html#understand-default-locations-with-examples) (Spark only).

What we can do here is add an extra condition for the warning.
1. startswith `dbfs` (no warning as is)
2. startswith local path `/` or relative path (show warning as is)
3. startswith `s3` or equivalent (use `CLOUD_PROTOCOL`) (new change)

**Comment by astrojuanlu** [comment]
Thanks for the explanation @noklam. @alamastor would you like to send a pull request for this one?

**Comment by alamastor** [comment]
Thanks for the quick response!
> Is there a reason why you are not using dbfs when you are using Databricks already?
Using s3 directly seems to be working well, so there's no reason to for us to use dbfs.

I'm happy to do a PR - I'll try to get something up in the next week or so.

**Comment by noklam** [comment]
@alamastor Awesome! Have a look at https://github.com/kedro-org/kedro-plugins/blob/main/CONTRIBUTING.md and let us know if you need help. We are also reachable on slack.kedro.org

**Comment by alamastor** [comment]
PR for this [here](https://github.com/kedro-org/kedro-plugins/pull/341) :smile:
