### ISSUE TITLE
Bump s3fs dependency for kedro-datasets

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-plugins#346]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

Cc @MatthiasRoels 

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by MatthiasRoels** [comment]
Isn’t this a duplicate of https://github.com/kedro-org/kedro-plugins/issues/337?

**Comment by noklam** [comment]
@MatthiasRoels You are right :) Didn't notice this issue, I checked on phone sometimes it's a bit hard to navigate GitHub repository with the mobile app. Closing as duplicate. Are you still up for a PR?

**Comment by MatthiasRoels** [comment]
Absolutely! I am already working on it, but it turns out to be a lot harder than I expected :D
