### ISSUE TITLE
Release `kedro-datasets` `1.8.0`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#388]
### Changes that should go into this release:

- [x] https://github.com/kedro-org/kedro-plugins/pull/350 (Awaiting updates from author)
- [x] https://github.com/kedro-org/kedro-plugins/pull/281 
- [x] https://github.com/kedro-org/kedro-plugins/pull/341

### Moved to next release
- https://github.com/kedro-org/kedro-plugins/pull/352
- https://github.com/kedro-org/kedro-plugins/pull/360

**Comment by deepyaman** [comment]
> * [ ]  [perf(datasets): delay `Engine` creation until need #281](https://github.com/kedro-org/kedro-plugins/pull/281)

I _think_ I just need to implement this for Snowflake; will try and do this now. :fingers_crossed:
