### ISSUE TITLE
Deprecate `CSVDataset` in favour of `GenericDataset`?

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-plugins#390]
> Shouldn't we then also consider removing (or mark as deprecated) the `CSVDataset`? And as a follow-up: should we do the same with the pandas datasets? Basically, the `pandas.GenericDataset` replaces the CSV, Excel, Feather, JSON, Parquet and XML ones, which should make the code base leaner.

_Originally posted by @MatthiasRoels in https://github.com/kedro-org/kedro-plugins/issues/350#issuecomment-1742579414_

**Comment by merelcht** [comment]
Discussed this in backlog grooming and it was decided not to do this ticket right now:

- It's not entirely clear what user problem this solves, and if `pandas.GenericDataset` is the correct solution.
- If users like having the separation between datasets and dependencies, they would loose that when moving to GenericDataset
- We already have breaking changes on `kedro-dataset` merged in, so we wouldn't bet able to properly "deprecate" the datasets at this point in time.
