### ISSUE TITLE
Expand `kedro-airflow` instructions

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-plugins#394]
## Description
The `kedro-airflow` README explains that, to run a Kedro project in Airflow, one needs to package it and install it. what should the user do with the data and the `.tar.gz` file containing the catalog configuration? In other words, how does the Airflow DAG know where to locate both of these things?

I could not locate any videotutorials of anybody doing this.

**Comment by astrojuanlu** [comment]
Previous evidence of a user asking the same https://linen-slack.kedro.org/t/14153188/hello-kedroers-i-ve-been-trying-to-evaluate-kedro-airflow-pl#bae895ca-5a10-477c-adfd-cecf1d775131

**Comment by merelcht** [comment]
Can we close this now after all updates @DimedS and @ankatiyar made to the docs?

**Comment by DimedS** [comment]
> Can we close this now after all updates @DimedS and @ankatiyar made to the docs?

I believe so, that question was addressed in the recent documentation update.
