### ISSUE TITLE
Investigate `ManagedTableDataset` test failures

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro-plugins#399]
## Description
In #398 I've skipped the tests in `kedro-datasets/tests/databricks` for `ManagedTableDataset` to unblock release.
The CI failure is related to spark : https://github.com/kedro-org/kedro-plugins/actions/runs/6554307517/job/17801080336

Spike: investigate why the tests are failing and suggest a plan to fix the dataset.

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-plugins/pull/671.
