### ISSUE TITLE
Rename extra import with non capitalized "S" to "Dataset"

### ISSUE THREAD

**Issue by Galileo-Galilei** [kedro-org/kedro-plugins#403]
## Description
All Datasets have been rename without a capital "S", e.g. ``CSVDataSet``->``CSVDataset``: 

https://github.com/kedro-org/kedro-plugins/blob/b44bf0e9db43d1564e50bbc85c7a61676c1ddbe4/kedro-datasets/kedro_datasets/pandas/csv_dataset.py#L26

but most (not all) of the extra imports still use the capitalized version: 

https://github.com/kedro-org/kedro-plugins/blob/b44bf0e9db43d1564e50bbc85c7a61676c1ddbe4/kedro-datasets/setup.py#L31

## Context

We should aim for consistency, but maybe this will be done once the ``setup.py`` will be refactored to a ``pyproject.toml``?

**Comment by astrojuanlu** [comment]
We'll need to figure out alternative names anyway https://github.com/kedro-org/kedro-plugins/issues/313

**Comment by Galileo-Galilei** [comment]
Did not see that. I close the issue, sorry for the noise.
