### ISSUE TITLE
Release `kedro-datasets` `2.0.0`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#421]
### To do/check

- [x] Are all mentions of `DataSet` gone?: https://github.com/kedro-org/kedro-plugins/pull/465
- [x] Do all datasets have the keyword marker `*` in the `__init__` methods added in https://github.com/kedro-org/kedro-plugins/pull/358?: #466 
- [x] Finish and merge https://github.com/kedro-org/kedro-plugins/pull/348 -> https://github.com/kedro-org/kedro-plugins/pull/463
- [ ] Nice to have: [Make sure all example code blocks for datasets are runnable#2287](https://github.com/kedro-org/kedro/issues/2287)

**Comment by astrojuanlu** [comment]
If we're not in a hurry could we do https://github.com/kedro-org/kedro-plugins/issues/313 ? Or maybe too disruptive? (We can wait to 3.0)

**Comment by Galileo-Galilei** [comment]
I think 2.0.0 is also a good time to do #353, but there were concerns that it could affect ``kedro-viz``. Should we move on this one?

**Comment by noklam** [comment]
#313 I don't think we need to rush for that, it's slightly untidy for us to keep setup.py but it is not that bad.
#353 I tend to agree with the rename, though it may be too disruptive. Would it be too bad if we rename but keep an alias for `MatplotlibWriter`, and in docs we use `MatplotlibDataset` and keep a small note that it is aliased `MatplotlibWriter`?

**Comment by astrojuanlu** [comment]
> https://github.com/kedro-org/kedro-plugins/issues/313 I don't think we need to rush for that, it's slightly untidy for us to keep setup.py but it is not that bad.

https://github.com/kedro-org/kedro-plugins/issues/313#issuecomment-1798023519
