### ISSUE TITLE
Release `kedro-airflow` `0.8.0`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#437]
### Description
Release `kedro-airflow` `0.8.0` if changes are needed after the `0.19.0` release. 

### Context
`kedro-airflow` is pinned to `kedro>=0.17.5` and so might be affected by the `0.19.0` release. We know that the plugin will be impacted, so we will aim to release asap, but it's okay if it's broken for a couple of days.

**Comment by ankatiyar** [comment]
Closed by #491
