### ISSUE TITLE
Understanding the average size of a Kedro project

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-plugins#44]
# Description

One of the value propositions that Kedro supports is that it's suitable for large-scale analytics projects. A large-scale analytics project has many nodes, datasets and pipelines and might involve many team members. 

This task focuses on making it possible to collect data to support this value proposition via `kedro-telemetry`. Furthermore, I want an easy way to understand this data via Heap Analytics. 

## Context
Suppose we find this is not true in practice and the average Kedro project is small. In that case, it will affect some design choices and perhaps open up usability functionality that supports smaller projects, e.g. a YAML API for the pipelines and nodes. 

> We know that YAML is easier to work with; however, we have discouraged the YAML API pattern because it creates maintainability problems for large-scale projects. However, a YAML interface appears to be a pipeline creation pattern used by [Ploomber](https://docs.ploomber.io/en/latest/get-started/first-pipeline.html) and [MLFlow Pipelines](https://mlflow.org/docs/latest/pipelines.html), and it may suggest that projects are smaller, which is why users can get away with using it. This needs to be verified. 

## Possible Implementation

This task will require us being able to find out a few things: 

To work out the size of a Kedro project, probably tracked per `username` (following work on HEAP): 

- [ ]  Number of datasets
- [ ]  Number of nodes
- [ ]  Number of pipelines

 - To work out how many team members are on a project, to show that Kedro helps with collaboration: 
- [ ]    Number of projects, identified by `project_name` 
- [ ]    A count of `username` per project

## Possible Alternatives

Another wild idea is that we may be able to find this information by counting elements on Kedro-Viz. Kedro-Viz already has a way to find large-scale pipelines when the [pipeline warning graph appears](https://heapanalytics.com/app/env/2388822444/graph/report/preview/1999755). However, this information is incomplete because it assumes that users are also using Kedro-Viz and I'm also not sure what size of the pipeline will trigger the warning. 

![Screenshot 2022-07-11 at 11 38 55](https://user-images.githubusercontent.com/43755008/178246688-65b443f9-ab8c-4a4f-bca1-8bddc8790d8b.png)

**Comment by MerelTheisenQB** [comment]
**If possible add:**
Size of projects by internal vs external users

**Nice to have:**
Could we figure out what parts of a pipeline are data engineering vs data science specific?

**Comment by MerelTheisenQB** [comment]
This issue was discussed as part of a **Technical Design** session:

- Size should be determined by the number of nodes in the default pipeline and the number of dataset entries in the catalog
- Currently we use the `before_command_run` hook, but to send the size info to heap we'd also need to either use the `before_pipeline_run` or `after_context_created` hook. 
- To be decided by the person implementing this: inside `kedro-telemetry` would we do a call to the Heap API for every Kedro hook that's called, or do we aggregate the data fetched in the hooks and then send it to Heap in one call?
