### ISSUE TITLE
Kedro-airflow issue: cannot find configuration path  /conf/base

### ISSUE THREAD

**Issue by arumds** [kedro-org/kedro-plugins#46]
## Description
I am starting to use airflow for a kedro  ML project. I have airflow installed on MAC.  I have a kedro project which runs successfully on my local MAC. Currently, trying to convert the kedro pipeline to an airflow executable task.

To do this, I have followed the instructions at https://github.com/quantumblacklabs/kedro-airflow

1. kedro airflow create 

2. Copied the created dag to the airflow dags/ folder

3. kedro package

This step created the dist/ with .whl and .egg files

4. checkpoints:
```
% which airflow
/Users/sl/mambaforge-pypy3/envs/airflow_env/bin/airflow
(airflow_env) % which python 
/Users/sl/mambaforge-pypy3/envs/airflow_env/bin/python
```
5. The kedro package from step 3 is installed to airflow executors venv:

` /Users/sl/mambaforge-pypy3/envs/airflow_env/bin/python -m pip install /dist/test_uk-0.1-py3-none-any.whl
`

Now the docs https://kedro.readthedocs.io/en/stable/deployment/single_machine.html#package-based suggest that

`pyproject.toml` file `conf/` and `data/`, `logs/` have to be created and are not packaged in step 3. 

Therefore, I have created these directories in the below location:

```
 % pwd
/Users/sl/mambaforge-pypy3/envs/airflow_env/lib/python3.10/site-packages/test_uk
(airflow_env) sl@MacBook-Pro test_uk % ls
__init__.py		__pycache__		data			logs			pipelines		settings.py
__main__.py		conf			info.log		pipeline_registry.py	pyproject.toml
```
## Context

```
This gives the below error:

[2022-07-15, 20:54:59 EEST] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/sl/airflow/dags/test_uk_dag.py", line 36, in execute
    with KedroSession.create(self.package_name,
  File "/Users/sl/mambaforge-pypy3/envs/airflow_env/lib/python3.10/site-packages/kedro/framework/session/session.py", line 172, in create
    session._setup_logging()
  File "/Users/sl/mambaforge-pypy3/envs/airflow_env/lib/python3.10/site-packages/kedro/framework/session/session.py", line 188, in _setup_logging
    conf_logging = self._get_logging_config()
  File "/Users/sl/mambaforge-pypy3/envs/airflow_env/lib/python3.10/site-packages/kedro/framework/session/session.py", line 176, in _get_logging_config
    conf_logging = self._get_config_loader().get(
  File "/Users/sl/mambaforge-pypy3/envs/airflow_env/lib/python3.10/site-packages/kedro/config/templated_config.py", line 161, in get
    config_raw = _get_config_from_patterns(
  File "/Users/sl/mambaforge-pypy3/envs/airflow_env/lib/python3.10/site-packages/kedro/config/common.py", line 69, in _get_config_from_patterns
    raise ValueError(
ValueError: Given configuration path either does not exist or is not a valid directory: /conf/base
[2022-07-15, 20:54:59 EEST] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=test-uk, task_id=preprocess, execution_date=20220714T050000, start_date=20220715T145449, end_date=20220715T145459
[2022-07-15, 20:54:59 EEST] {standard_task_runner.py:92} ERROR - Failed to execute job 8 for task preprocess (Given configuration path either does not exist or is not a valid directory: /conf/base; 85230)
[2022-07-15, 20:54:59 EEST] {local_task_job.py:156} INFO - Task exited with return code 1

```

Then i tried creating these directories in airflow/ where the dags/ are located

```
 airflow % ls
airflow-scheduler.err		airflow-webserver-monitor.pid	airflow-webserver.pid		dags				webserver_config.py
airflow-scheduler.log		airflow-webserver.err		airflow.cfg			data
airflow-scheduler.out		airflow-webserver.log		airflow.db			logs
airflow-scheduler.pid		airflow-webserver.out		conf				pyproject.toml
```

And i still get the same above error. I ran out of ideas and spent a couple of days trying different things. It could be an obvious thing  but im blinded at the moment. Any help would be highly appreciated.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):0.18.1
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`): Version: 0.5.0
* Python version used (`python -V`): Python 3.10.4
* Operating system: MacOs Monterey (M1):

**Comment by allenhaozi** [comment]
hi @arumds 
Here's my solution:

add the following code to pandas_iris_01_dag.py

```python
sys.path.append("~/airflow/dags/pandas_iris_01/src")
```

upgrade project_path from  `Path.cwd()` to 
```python
project_path = "~/airflow/dags/pandas_iris_01"
```
```
(airflow) mahao@[~/airflow/dags]$ls
__pycache__           pandas_iris_01        pandas_iris_01_dag.py
```
```
(airflow) mahao@[~/airflow/dags]$tree -L 2
.
├── __pycache__
│   ├── demo.cpython-38.pyc
│   └── pandas_iris_01_dag.cpython-38.pyc
├── pandas_iris_01
│   ├── README.md
│   ├── __pycache__
│   ├── conf
│   ├── data
│   ├── docs
│   ├── info.log
│   ├── logs
│   ├── notebooks
│   ├── pyproject.toml
│   ├── setup.cfg
│   └── src
└── pandas_iris_01_dag.py

9 directories, 7 files
```

**Comment by allenhaozi** [comment]
But I met new error
```
ValueError: Pipeline input(s) {'X_test', 'y_train', 'X_train'} not found in the DataCatalog

```

**Comment by merelcht** [comment]
Hi @arumds, sorry for the incredibly late response. This ticket must have slipped the team's attention. Is there anything we can do to still help resolve your issued with using `kedro-airflow`?

**Comment by merelcht** [comment]
I'm closing this issue for now due to inactivity. Let us know if you need more help fixing this @arumds 🙂
