### ISSUE TITLE
[kedro-docker] Add creation of compose.yml file

### ISSUE THREAD

**Issue by yurigba** [kedro-org/kedro-plugins#47]
## Description
I would use more kedro-docker if it could generate a compose.yml file to configure volumes and other components manually. Instead of using kedro docker I could just replicate the configuration and use docker-compose directly, making it easier to integrate. Also it gives more freedom to make some tweaks with kedro-viz and other plugins.

## Context
I tend to not use directly kedro docker, and instead I create my own docker-compose, but kedro docker init already helps a lot.

## Possible Implementation
Make `kedro docker init` create a compose.yml file that makes it possible to run via `docker-compose up`

**Comment by noklam** [comment]
@yurigba Thanks for creating this thread. Is this something that you may be interested to implement?

> Also it gives more freedom to make some tweaks with kedro-viz and other plugins.
Can you share more details about what you are trying to do with it?
