### ISSUE TITLE
Fix kedro-airflow CI

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-plugins#481]
> The tests are outdated.  `kedro-airflow/features/steps/cli_steps.py` refers to `pandas-iris` on L162

_Originally posted by @sbrugman in https://github.com/kedro-org/kedro-plugins/issues/241#issuecomment-1853389105_

**Comment by ankatiyar** [comment]
I'll update it in https://github.com/kedro-org/kedro-plugins/pull/478
