### ISSUE TITLE
Update `kedro-telemetry` to use the `CI` environment variable to indicate that data comes from a CI environment

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-plugins#483]
### Description
Use the `CI` environment variable to differentiate runs between a CI/CD environment and a real kedro project run for data collection.

https://github.com/kedro-org/kedro/issues/1640#issuecomment-1162000302
> I think it would be good to take this opportunity to distinguish CI runs in telemetry. Maybe can read an environment variable; most CI systems ([GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables), [CircleCI](https://circleci.com/docs/2.0/env-vars#built-in-environment-variables), [Travis CI](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables), etc.) follow the convention of setting CI=true, so I would recommend detecting presence of the environment variable, solving the telemetry prompt automatically, and recording commands as belonging to a CI run--and ideally not requiring any additional configuration or hacks to avoid this telemetry prompt.

Whoever pick up this ticket should double check if `CI` is a standard convention we can use. Alternatively, we can refer to how Dagester do it:
https://github.com/dagster-io/dagster/blob/e31e577b8841e0ff54745e206d621d9bf934a063/python_modules/dagster/dagster/_core/telemetry.py#L92

**Comment by astrojuanlu** [comment]
Example: How Dagster does it: https://github.com/dagster-io/dagster/blob/e31e577b8841e0ff54745e206d621d9bf934a063/python_modules/dagster/dagster/_core/telemetry.py#L92-L101
