### ISSUE TITLE
Replace `identity` in kedro telemetry with unique `username`

### ISSUE THREAD

**Issue by SajidAlamQB** [kedro-org/kedro-plugins#50]
## Description
This is related to the [heap issue](https://github.com/kedro-org/kedro-plugins/issues/36). Looking at the kedro-telemetry plugin we currently assign the hashed computer name of users to the `identity` parameter for Heap. Having a look at the Heap API it makes more sense to assign this to something like `username`. 

Note: The identity parameter needs to be unique, so we may want to find a way to ensure this. (Maybe we hash the concatenation of username and computer name?)

Reason for this:
[Heap generates](https://developers.heap.io/docs/using-identify#anonymous-to-existing-identity) a unique userID that can't be manually changed and isn't related/mapped to the `username` parameter. However, if heap finds the same `identity` it will merge that userID into the Heap profile of the identified user.

## Context
https://github.com/kedro-org/kedro-plugins/issues/36

**Comment by yetudada** [comment]
Thank you so much for the investigation on this @SajidAlamQB! I think this is a sensible solution for the matching the user IDs. I don't think we need to combine the `hashed_username` with `hashed_computer_name` because they're both hashed.  `hashed_username` should be enough.
