### ISSUE TITLE
Adding connection kwargs to SQL Datasets engine creation

### ISSUE THREAD

**Issue by takikadiri** [kedro-org/kedro-plugins#505]
## Description
We use `SQLQueryDataSet` and `SQLTableDataSet` to load data from databases. Sometimes we need to pass some args to the underlying engine at creation time.

## Context
We want to use duckdb to load some parquet data from s3 using the `SQLQueryDataSet`.  However, we need to pass some `connect_args` to the sqlalchemy engine, so it can point to the right s3 with the right config. Currently, [only the connection url is passed to the `create_engine`
](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/pandas/sql_dataset.py#L494)  
This could be also valuable when doing multiple pipeline runs. For example, in a web service scenarios, a user will probably need to configure among other the connection pooling.

## Possible Implementation
Adding an `args` entry to the `credentials`, and passing this `args` as a kwargs to the `create_engine`. 

Knowing that the connection object is a singleton, that is unique to the connection uri, introducing a connection args raise some questions about what we should consider as a condition of a connection unicity. Is it the connection uri or the connection uri + connection args ?

**Comment by astrojuanlu** [comment]
Hi @takikadiri, thanks for bringing this to our attention. For reference, here's the code:

https://github.com/kedro-org/kedro-plugins/blob/94019fd6e724af9cbacfc7b7fb9678e897a435d2/kedro-datasets/kedro_datasets/pandas/sql_dataset.py#L493C1-L494

And here's the relevant sqlalchemy docs https://docs.sqlalchemy.org/en/20/core/engines.html#use-the-connect-args-dictionary-parameter

**Comment by noklam** [comment]
@takikadiri is this solved by https://github.com/kedro-org/kedro-plugins/pull/564/files#diff-de532a447f03c94163b260b67c40673ddf58d8b23a038cb09669c0931c549a0f already?

**Comment by takikadiri** [comment]
@noklam yes this is exactly what i needed 😄 thank you for bringing this to my attention and thanks @mjspier for this contribution.

I didn't test it yet, but it looks good for me. We can close this issue
