### ISSUE TITLE
Update our `kedro-telemetry` documentation on which data is collected

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-plugins#508]
## Description

I was poking around on the [`kedro-telemetry` README.md](https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry) and realised the table which shows which data we collect is out of date. It's missing fields like `username`, project size (#44) and even notes on `tools` used. Additionally, we should mention that Kedro-Viz UI interactions are captured too. 

## Context
We should be transparent on all information we collect about our users. This task just requires getting the most accurate view of the information `kedro-telemetry` pulls and updating the table.

**Comment by astrojuanlu** [comment]
Also, it mentions hostname, but hostname hashing was removed in https://github.com/kedro-org/kedro-plugins/pull/58/

**Comment by stichbury** [comment]
See further information on #509 about the location of updates and additional task to fix a broken link in https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry#privacy-notice

**Comment by astrojuanlu** [comment]
For the record,

> I think it would make sense to have a better coverage of telemetry in the main docs (this could be in the plugins section perhaps) and link that through to the README.

(from #509)

cc @DimedS

**Comment by astrojuanlu** [comment]
We were advised that the text should indicate clearly that

1. We are not collecting any personal data
2. The data is collected with the purpose of understanding and improving the product, never for marketing or promotional purposes

For now there are some examples in https://github.com/kedro-org/kedro-plugins/issues/510#issuecomment-1885237973, if I find a better template we can use I'll paste it here.

**Comment by astrojuanlu** [comment]
Reopening this until we merge https://github.com/kedro-org/kedro/pull/3603
