### ISSUE TITLE
kedro-airflow: add a cli option `--tags` to filter nodes by tags

### ISSUE THREAD

**Issue by jw-cpnet** [kedro-org/kedro-plugins#516]
## Description
I used to use --params and custom jinja2 template to cover most of my use cases. Except for this one: when I want to generate a dag from a part of my pipeline, I can't. I know I can pass tags via --params but it won't work, because the node dependency can not be changed there.

## Context
I found this very useful because sometimes I only want to generate a dag from a partial pipeline. For example, one of my nodes can run DDL but I don't need it to run repeatedly when I generate the dag for airflow.

## Possible Implementation
I have implemented a simple one: [here](https://github.com/jw-cpnet/kedro-airflow-fusion/commit/088d926599b63fade88f5fc41672936e50978b01)

If you guys are interested, I will raise a PR.

Sorry for my poor English.

**Comment by astrojuanlu** [comment]
Thanks @jw-cpnet! We have a bit of a backlog for `kedro-airflow` but we'll be working on it in the coming days and we hope to get back to you soon.

**Comment by noklam** [comment]
i think that something we're interested to accept. IMO it should mirror what `kedro run` does, probably should follow exactly the same mechanism to make sure it's consistent.
