### ISSUE TITLE
Check Telemetry data accuracy and add example_pipeline information

### ISSUE THREAD

**Issue by DimedS** [kedro-org/kedro-plugins#543]
## Description

1. During the telemetry collection process, we gather data on the number of datasets, nodes, and pipelines within a project, as well as the tools selected. 

After executing `kedro new`, selecting tools 1-5, and setting `example=y`, I visited the Heap website to review the collected data for that session. The data retrieved included three lines:
<img width="1590" alt="Screenshot 2024-02-07 at 12 37 43" src="https://github.com/kedro-org/kedro-plugins/assets/40151847/5d4d3eca-cff7-4172-8958-bd036bf10ee0">

 but it lacked information regarding the tools I had chosen. Additionally, the reported numbers appeared to be inaccurate; the spaceflights-pandas starter actually contains 2 pipelines, 7 datasets, and 6 nodes:
<img width="480" alt="Screenshot 2024-02-07 at 12 38 06" src="https://github.com/kedro-org/kedro-plugins/assets/40151847/9d4c2e46-a3b8-40a7-b817-e1ae8a3433c7">

2. Additionally, we should include the `example_pipeline` option in our data collection (already stored in `pyproject.toml`) to gather information alongside the selected tools.

## Your Environment
<img width="492" alt="Screenshot 2024-02-07 at 12 36 09" src="https://github.com/kedro-org/kedro-plugins/assets/40151847/fe5d50af-a4bf-4892-9b09-23b66d7924ff">

**Comment by astrojuanlu** [comment]
> Additionally, the reported numbers appeared to be inaccurate; the spaceflights-pandas starter actually contains 2 pipelines, 7 datasets, and 6 nodes:

I suspect

- We're counting `__default__` as an extra pipeline,
- We're counting `params:` as datasets

About `__default__`, it's unclear what should we do here - I think it's correct to include it, after all users could as well delete the default code in `pipeline_registry.py`. For `params:` being counted as datasets, probably they should not be accounted.

> it lacked information regarding the tools I had chosen

I recall doing an experiment early on and seeing them. Let's look into it.

> Additionally, we should include the example_pipeline option in our data collection (already stored in pyproject.toml) to gather information alongside the selected tools.

Agreed 👍🏽

**Comment by DimedS** [comment]
we should update kedro docs - add example_pipeline in Telemetry collection chapter
