### ISSUE TITLE
Investigate deltalake changes and why they broke our test

### ISSUE THREAD

**Issue by SajidAlamQB** [kedro-org/kedro-plugins#550]
## Description
Context: https://github.com/kedro-org/kedro-plugins/pull/541

In #541 we pinned deltalake to <0.15.2, we suspect some underlying changes the way data is appended and retrieved in their code broke our test. We should investigate this further and see if we can adapt our `DeltaTableDataset`.

## Possible Implementation
If the change isn't significant we can just sort before comparing the DataFrames in our tests.

**Comment by merelcht** [comment]
This was fixed in https://github.com/kedro-org/kedro-plugins/pull/617
