### ISSUE TITLE
Telemetry data for tools and example_pipeline is not collected in packaged Kedro projects

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-plugins#567]
When a user creates a Kedro project using `kedro new`, packages it with `kedro package`, and subsequently installs and runs it using `project_name`, the `pyproject.toml` file, which serves as a source for telemetry data about `tools` and the `example_pipeline`, is not present. As a result, telemetry submissions to Heap include a singular event labeled "Kedro Project Statistics," devoid of details on `tools` and the example `pipeline`.

For further discussion, see [here](https://github.com/kedro-org/kedro-plugins/pull/557#issuecomment-1956803595).

(Comes from @DimedS on https://github.com/kedro-org/kedro-plugins/issues/566)

**Comment by merelcht** [comment]
Discussed in grooming that collecting information about `tools` and `example` for packaged project isn't a priority.
