### ISSUE TITLE
Update airflow documentation for latest version of airflow

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-plugins#573]
Another task that comes out of https://github.com/kedro-org/kedro/issues/2435

* `kedro-airflow-k8s` isn't available for Kedro >0.17 (but this is for GetInData to update)
* Our airflow/astronomer tutorial isn't for the latest Airflow versions

It would be sensible to run through the docs that we are responsible for to confirm they are still OK for the latest version, and meanwhile to caution the reader as to the limitations of version support as noted above.

**Comment by merelcht** [comment]
Closing in favour of https://github.com/kedro-org/kedro-plugins/issues/605
