### ISSUE TITLE
The kedro_datasets.huggingface.HFDataset class have to accept parameters optionals in call of the function

### ISSUE THREAD

**Issue by eromerobilbomatica** [kedro-org/kedro-plugins#574]
## Description
The kedro_datasets.huggingface.HFDataset class have to accept parameters optionals in call of the function and are not defined in the catalog code.

## Context
How has this bug affected you? What were you trying to accomplish?

I have been trying to load a hugging face dataset with this code:
````
dataset_hf:
  type: kedro_datasets.huggingface.HFDataset
  dataset_name: Davlan/sib200
````

I get this error:

![image](https://github.com/kedro-org/kedro-plugins/assets/144208874/0555739e-1d88-487a-ab25-7af5e9612248)

There are some dataset that needs some optional parameters when you call the function. See link [https://huggingface.co/docs/datasets/package_reference/loading_methods#datasets.load_dataset](https://huggingface.co/docs/datasets/package_reference/loading_methods#datasets.load_dataset)

**Comment by astrojuanlu** [comment]
Thanks @eromerobilbomatica ! 

I think the solution is to add a `dataset_kwargs`, like

https://github.com/kedro-org/kedro-plugins/blob/afe4c98cd6a18a2e2e217989a5fe70a6a9d1d2c4/kedro-datasets/kedro_datasets/huggingface/transformer_pipeline_dataset.py#L43
