### ISSUE TITLE
Decide on name for experimental contribution space in `kedro-datasets`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#577]
## Description
Following the initial discussion in #517, it was decided we'll add a contrib/experimental directory inside the `kedro-datasets` repo for experimental contributions. We did not decide on a name for this space yet, so that will need to be done before it's created.

## Context
Different projects use different terminology when referring to (experimental) contributions, in the original proposal `contrib` was put forward, but in the discussions some team members mentioned they didn't like the name and preferred `experimental`. 

## Possible names
- `contrib`
- `experimental`
- `prototypes`
- `dataset-experiments`
- `dataset-prototypes`
- `unstable`
- `incubator`

**Comment by astrojuanlu** [comment]
How is the decision process going to look like? Should we rank proposals, pick our preferred ones, use some online Condorcet Voting tool?

**Comment by merelcht** [comment]
![image](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZDB5amZ1MTI2YXJ5c3E5cTZjeHJxYnB1OXByMDJrOXhrem5wNXNmdSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3ohjUStHuiE5YtAUrC/giphy.gif)

**Comment by merelcht** [comment]
The results of a vote on "What name should we give to name the experimental contribution space in `kedro-datasets`?" are as follows: 

<img width="1476" alt="Screenshot 2024-03-07 at 16 28 59" src="https://github.com/kedro-org/kedro-plugins/assets/49397448/f1c19a73-5510-415b-8c48-4b2d1c251eeb">

The majority of votes is for `experimental`, so that will be the name of the experimental contribution directory.
