### ISSUE TITLE
Determine demotion process of dataset contributions

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#582]
## Description
Datasets within the regular `kedro_datasets` contributions folder may deterioriate and get outdated over time. We might then need to decide to demote these datasets back to the experimental contributions space.

We need to establish clear criteria and guidelines for determining when a regular contribution needs to be demoted.

## Task

- Decide what the criteria are for "regular" contributions (overlaps with #581)
- Decide what the process is to demote a dataset.
- Document as part of #579

**Comment by merelcht** [comment]
My suggestion for demoting datasets is as follows:

## Demotion process of datasets

We should consider demoting a dataset from a “regular” contribution back to the experimental contribution space when:

- The quality of the dataset no longer meets the standards of a regular dataset contribution and is not fixable:
    - Dependencies no longer supported/maintained
    - Doesn’t work on all supported Python versions
    - Doesn’t work on Windows and/or Linux anymore

The Kedro team should consider regular datasets as our responsibility just as the majority of the Kedro codebase, and demoting a dataset shouldn't be done lightly as it basically means discontinuing formal support.

**Comment by yetudada** [comment]
It's brilliant that you're thinking of this!

**Comment by deepyaman** [comment]
Just throwing it out there—is it possible primary maintainer leaves, and there isn't anybody on the TSC who wants to commit to maintaining it? Or we just force it upon somebody/collective responsibility at that point? :)

**Comment by merelcht** [comment]
Closing this in favour of continuing the discussion in #583 

Bottom line is that the following make up the demotion process:
1. The demotion process will be triggered by someone from the TSC when a dataset isn’t deemed fit as a regular contribution anymore. 
2. We need 1/2 approval from the TSC to initiate a review/merge to the experimental datasets space.
