### ISSUE TITLE
Missing default value for connection_args in SQLTableDataset.create_connection()

### ISSUE THREAD

**Issue by jerome-asselin-buspatrol** [kedro-org/kedro-plugins#585]
Wouldn't we need to default the `connection_args` with an empty dict? That argument has been recently added with no default.

https://github.com/kedro-org/kedro-plugins/blame/db928927490787b41f72a58c6e08acc0e4b97b29/kedro-datasets/kedro_datasets/pandas/sql_dataset.py#L228

Suggested change:
```
def create_connection(cls, connection_str: str, connection_args: dict = {}) -> None:
```

Regards,

**Comment by astrojuanlu** [comment]
Good point @jerome-asselin-buspatrol , we overlooked that during review. Would you like to send a PR yourself?

**Comment by jerome-asselin-buspatrol** [comment]
I would be honored to do so. Let me try...

**Comment by jerome-asselin-buspatrol** [comment]
Hmm... I'm having a hard time creating a branch. Any advice?

If it's easier, my suggested change is as follows:
```
    def create_connection(cls, connection_str: str, connection_args: dict = None) -> None:
        """Given a connection string, create singleton connection
        to be used across all instances of ``SQLTableDataset`` that
        need to connect to the same source.
        """
        connection_args = connection_args or {}
```

**Comment by astrojuanlu** [comment]
You'd have to fork the repository before creating the branch 
![image](https://github.com/kedro-org/kedro-plugins/assets/316517/7a8c8527-e62f-45df-9282-881bdbfbeb24)

but yes, that should be the change we'd want to apply

**Comment by jerome-asselin-buspatrol** [comment]
Here is the proposed fix. https://github.com/kedro-org/kedro-plugins/pull/586

I see many tests failing in the github actions, but I think those are not related to my changes. Are they?

**Comment by astrojuanlu** [comment]
They're not, our nightly builds also failed. We're looking into it.

**Comment by astrojuanlu** [comment]
#586 was merged!
