### ISSUE TITLE
Kedro-airflow python-slugify version pin is incompatible with latest version of airflow

### ISSUE THREAD

**Issue by cshaley** [kedro-org/kedro-plugins#60]
## Description
kedro-airflow pins python-slugify with python-slugify~=4.0
airflow pins python-slugify with python-slugify>=5.0 and supports the latest version of python-slugify.
A pin of python-slugify>=4.0,<7 would be great if kedro-airflow can support it.

## Context
I was trying to pip install kedro-airflow with the latest version of airflow and got a deoendency resolution error.

## Steps to Reproduce
1. pip install apache-airflow==2.3.4 kedro-airflow
2. Receive error

## Expected Result
Ideally you can install both in the same environment.

## Actual Result
You receive an error: 
```
ERROR: Cannot install apache-airflow==2.3.4 and kedro-airflow==0.5.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    apache-airflow 2.3.4 depends on python-slugify>=5.0
    kedro-airflow 0.5.0 depends on python-slugify~=4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:
Not applicable 

* Kedro version used (`pip show kedro` or `kedro -V`):
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`):
* Python version used (`python -V`):
* Operating system and version:

**Comment by deepyaman** [comment]
@cshaley Yep, I ran into this also on #52. I also removed the bound on `sqlalchemy` (similar issue, where Kedro requires `sqlalchemy<1.4` and `airflow>=2.3` requires `sqlalchemy>=1.4`. Hope to resolve this soon and get your updated Kedro-Airflow release!

**Comment by cshaley** [comment]
Awesome, looking forward to it!

**Comment by rxm7706** [comment]
@deepyaman any update on https://github.com/kedro-org/kedro-plugins/pull/52

**Comment by deepyaman** [comment]
> @deepyaman any update on #52

@rxm7706 @cshaley I'm really sorry, I dropped the ball on this one. We've marked this as high priority and hope to wrap up any loose ends in the following sprint.

**Comment by merelcht** [comment]
Another related issue: https://github.com/kedro-org/kedro-plugins/issues/73
