### ISSUE TITLE
Python `3.12` support for `kedro-plugins`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#613]
### Description

Now https://github.com/kedro-org/kedro/issues/3287 is done, we should add Python `3.12` to all plugins as well.

- [x] `kedro-telemetry` #615 
- [x] `kedro-airflow` #614 
- [x] `kedro-docker` #616 
- [x] `kedro-datasets` #617

**Comment by ankatiyar** [comment]
Completed by the PRs mentioned in the description ^
