### ISSUE TITLE
Experimental dataset contribution model

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#629]
### Description
Introduce a new contribution folder within the Kedro datasets repository to accommodate contributions that are more experimental and may not fully adhere to the usual standards, such as being fully tested. This space will allow for the inclusion of datasets that are in the early stages of development or might not meet the criteria for being part of the core Kedro datasets.

An example of such datasets are the langchain based datasets for which we have an open draft PR: https://github.com/kedro-org/kedro-plugins/pull/434

### Milestone tasks
https://github.com/kedro-org/kedro-plugins/milestone/7

**Comment by astrojuanlu** [comment]
You mentioned that the last item here is figuring out the docs @merelcht ?

**Comment by merelcht** [comment]
> You mentioned that the last item here is figuring out the docs @merelcht ?

@astrojuanlu Yes, I moved one contribution that's in progress to experimental and the docs for that are now failing: https://github.com/kedro-org/kedro-plugins/pull/355. I'll create a ticket for fixing that.
