### ISSUE TITLE
Release `kedro-datasets` 3.0.0

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#632]
### Description
Release `kedro-datasets` `3.0.0`. Also needed for `kedro-viz` release.

Blocked by:

- [x] https://github.com/kedro-org/kedro-plugins/pull/595
- [x] https://github.com/kedro-org/kedro-plugins/pull/560

**Comment by astrojuanlu** [comment]
Looks like we'll need to tackle https://github.com/kedro-org/kedro-plugins/issues/609, any chance we can do that so we can merge #560 before we release?
