### ISSUE TITLE
Add python 3.12 support to `kedro-airflow`

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro-plugins#634]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

Waiting on `apache-airflow` 2.9 release

**Comment by astrojuanlu** [comment]
Related: https://www.astronomer.io/events/webinars/whats-new-in-airflow-2-9-video/

**Comment by astrojuanlu** [comment]
https://github.com/apache/airflow/releases/tag/2.9.0 🎉

**Comment by ankatiyar** [comment]
@astrojuanlu amazing, on it!

**Comment by ankatiyar** [comment]
Waiting on Kedro release now! 😬

**Comment by ankatiyar** [comment]
#613 is still open, will do it as a part of that
