### ISSUE TITLE
Release kedro-airflow

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#675]
### Description
Includes grouping of in-memory nodes and 3.12 support

**Comment by ankatiyar** [comment]
Could this wait till after the tech design discussion - I wanted to suggest a change in the design of `--group-by-memory` 
#673 so that if/when we decide to add more grouping strategies, it's not a breaking change. 😄

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-plugins/pull/698.
