### ISSUE TITLE
kedro-datasets: missing metadata parameter

### ISSUE THREAD

**Issue by michal-mmm** [kedro-org/kedro-plugins#699]
## Description
Currently, not all datasets have a `metadata` parameter.

## Context
Some `kedro` plugins use this parameter to extend basic functionality (e.g. [kedro-viz](https://github.com/kedro-org/kedro-viz), [kedro-pandera](https://github.com/Galileo-Galilei/kedro-pandera)).

## Steps to Reproduce
Examples:
https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/databricks/managed_table_dataset.py#L217 - `ManagedTableDataset`
https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/polars/eager_polars_dataset.py#L61 - `EagerPolarsDataset`

## Expected Result
All datasets should have a `metadata` parameter.

**Comment by astrojuanlu** [comment]
Thank you @michal-mmm !
