### ISSUE TITLE
Add `PyTorch` dataset to save models instead of using pickle

### ISSUE THREAD

**Issue by bpmeek** [kedro-org/kedro-plugins#714]
## Description
Pickle has known [security issues](https://www.synopsys.com/blogs/software-security/python-pickling.html#:~:text=process%20of%20unpickling.-,Dangers%20of%20Python%20pickling,data%20received%20over%20the%20network.), as of version 1.6 PyTorch now uses a [zip file-based](https://pytorch.org/tutorials/beginner/saving_loading_models.html#:~:text=.eval()-,NOTE,-The%201.6%20release) format instead of pickle. 

## Context
I think we should support the preferred method of loading and saving models, PyTorch is a very popular ML Library.

**Comment by DimedS** [comment]
Hi @bpmeek , thanks for raising this issue! This sounds like a very reasonable proposal. If you're interested in contributing to this development, we recently introduced a special experimental datasets space: [Kedro Datasets Experimental](https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets/kedro_datasets_experimental).

If not, I can add it to our regular sprint prioritisation process.

**Comment by bpmeek** [comment]
@DimedS I'd love to, thanks!
