### ISSUE TITLE
`kedro-telemetry`: Introduce environment variables for disabling telemetry and revise disabling methods

### ISSUE THREAD

**Issue by DimedS** [kedro-org/kedro-plugins#728]
## Description
Part of https://github.com/kedro-org/kedro-plugins/issues/715:

Introduce two new environment variables for disabling telemetry:
- `DO_NOT_TRACK`
- `KEDRO_DISABLE_TELEMETRY`
When either of these variables is set to True or 1, telemetry should not be used. This will have the same effect as setting `consent: false` in the `.telemetry` file, but without the need to modify the file. We will only check the consent.

## Context
Detailed explanation provided by @astrojuanlu in [this comment](https://github.com/kedro-org/kedro-plugins/issues/715#issuecomment-2161181479).

When all the opt-out tasks for #715 are completed these should be the ways to disable telemetry:
1. Environment Variables:
Set the environment variables `DO_NOT_TRACK` or `KEDRO_DISABLE_TELEMETRY` to 1. Setting either of these variables will fully disable telemetry for all projects in that environment.
2. Telemetry File:
Create a `.telemetry` file in the root folder of the Kedro project and write there `consent: false`. This disables telemetry for any kedro command executed within that project's folder.
3. CLI Option when creating a new project:
When creating a new project, users can use the command `kedro new --telemetry=yes/no`. This will create a `.telemetry` file with `consent: true/false` accordingly. However, telemetry data about the execution of the kedro new command will still be sent after #729 implementation.
4. `pip uninstall kedro-telemetry`
5. CLI telemetry Disable for each command execution:
Previously, we attempted to implement a CLI consent disable for `kedro run` command (see [Issue 2867](https://github.com/kedro-org/kedro/issues/2867)), but it was reverted due to unclear initial design. Considering the shift to an opt-out model, I believe @ankatiyar's [proposal](https://github.com/kedro-org/kedro-plugins/pull/681#issuecomment-2127020217) to provide consent for each execution of certain Kedro commands is still relevant. 

**Let's discuss this proposal**:
- Implement a `--no-telemetry` flag for `kedro run` and possibly other commands: `kedro run --no-telemetry`.
- This flag will disable telemetry only for that execution of that particular command.
- This can be beneficial for users who want to run their projects in CI/CD processes without needing to set environment variables.

**Comment by astrojuanlu** [comment]
4. `pip uninstall kedro-telemetry`

Does this conflict with #726? We should not counsel users to remove mandatory dependencies to avoid having `pip` showcase warnings of broken environments.

5. CLI telemetry Disable for each command execution

Wondering if this granularity is excessive. I wouldn't see users wanting to disable telemetry for some commands, but not others.

**Comment by noklam** [comment]
Few questions for @DimedS :
- At which point telemetry tracking is started? It's ok if user have access to a terminal and export the environment variable before launch kedro. What about people who want to set environment variable programatically, is there a preferred way to do so?
- Are all 5 ways to disable telemetry still valid/relevant under the context that telemetry is mandatory? As @astrojuanlu suggested, with the switch from opt-in -> opt-out, the `--no-telemetry` argument could be redundant as there will be no prompting with new project.

**Comment by astrojuanlu** [comment]
About --no-telemetry, we couldn't think of cases in which users would opt out for some commands, but not others. It's annoying to type every time too. I think it's not worth adding.
