### ISSUE TITLE
`kedro-datasets`: Connection credentials are exposed when `_describe()` for`ibis.TableDataset` 

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro-plugins#784]
## Description
Related https://github.com/kedro-org/kedro/issues/4024

## Context
In the `_describe()` method `self._connection_config` is exposed without filtering which will cause the exposure of credentials if those are set via configuration.

```
    def _describe(self) -> dict[str, Any]:
        return {
            "filepath": self._filepath,
            "file_format": self._file_format,
            "table_name": self._table_name,
            "connection_config": self._connection_config,
            "load_args": self._load_args,
            "save_args": self._save_args,
            "materialized": self._materialized,
        }
```

[BiqQuery connect configuration example](https://ibis-project.org/backends/bigquery#connection-parameters)
[MySQL connect configuration example](https://ibis-project.org/backends/mysql#ibis.mysql.connect)

**Comment by noklam** [comment]
Instead of excluding `connection_config`, we may want to included the interested keys only as the arguments are not consistent between different backend.

**Comment by ElenaKhaustova** [comment]
Solved in https://github.com/kedro-org/kedro-plugins/pull/786
