### ISSUE TITLE
Latest kedro `load` and `save` breaks `mypy` on datasets

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-plugins#793]
## Description

> kedro_datasets/pandas/json_dataset.py:210: error: "AbstractDataset[Any, Any]" has no attribute "_load"; maybe "load"?  [attr-defined]

https://github.com/kedro-org/kedro-plugins/actions/runs/10181415594/job/28161510649?pr=786

The root cause is now dataset cannot find the `_load` method as it's looking for signature of `AbstractDataset`, while the `_load` is implemented in `JSONDataset`

## Potential Fix
Use generic type instead of returing `AbstractDataset` in https://github.com/kedro-org/kedro/blob/8bbbfb6c7257005bef841143690308f05d4b829b/kedro/io/core.py#L403-L407

**Comment by deepyaman** [comment]
I'll update the datasets to use public load and save.
