### ISSUE TITLE
`kedro-telemetry`: remove recursive logic to avoid eagerly load commands

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-plugins#794]
# Context
![image](https://github.com/user-attachments/assets/622cbc40-43a0-4c75-8a8b-5a6b76567262)

I found out telemetry is loading all CLI commands which undermine the effort done in https://github.com/kedro-org/kedro/pull/3883.

# Impact
CLI is slow because telemetry always load all the commands.

# Description
At first glance, the recursive call does not seems to be necessary as it collects the entire CLI but they are not consume by telemetry later. Maybe all we need is the related command group. 1. is a small comment but we should check telemetry would work consistently for package mode as well.

> 1. `project_path` is not arbitary as it affects the result of recursive call
> 2. The recursive call undo the effort of LazyCommand as it eagerly import all the commands.
_Originally posted by @noklam in https://github.com/kedro-org/kedro-plugins/pull/775#pullrequestreview-2210638106_

**Comment by ankatiyar** [comment]
Can I take a stab at this 👀
