### ISSUE TITLE
`kedro-telemetry` showing error logs for not being able to read files

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#804]
## Description
After the `0.19.7` release which made telemetry a dependency of Kedro, error logs are shown similar to:
```
ERROR    Failed to read the file: /databricks/driver/pyproject.toml.              plugin.py:113
                             [Errno 2] No such file or directory: '/databricks/driver/pyproject.toml'       
```
See also https://github.com/kedro-org/kedro/issues/4066

## Context
On my side it's not causing build failures, but it's definitely a confusing error and I don't think this should be showing.

## Steps to Reproduce
1. Deploy a Kedro project as a Databricks Job with Kedro `0.19.7`
2. Check the logs

**Comment by ElenaKhaustova** [comment]
@merelcht it's already in work: https://github.com/kedro-org/kedro-plugins/issues/781
