### ISSUE TITLE
`kedro-datasets`: Improve dependency management for `spark` Datasets 

### ISSUE THREAD

**Issue by MigQ2** [kedro-org/kedro-plugins#849]
## Description
I want to discuss how we could improve the way dependencies are managed for `SparkDataSet` and similar

## Context
Currently `kedro-datasets[sparks]` installs pyspark, which is a >300MB monster package, and it's also probably unnecessary in most deployment setups.

When using Databricks, spark is already installed in the Databricks Cluster Runtime, and reinstalling vanilla pyspark just risks something breaking. 

If working locally with Databricks, [databricks-connect](https://docs.databricks.com/en/dev-tools/databricks-connect/python/index.html) is probably preferred and also installing vanilla pyspark risks breaking it

Also, installing the normal `kedro-datasets` without the `[spark]` suffix doesn't work, as `hdfs` doesn't get installed but [is needed in the code](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/spark/spark_dataset.py#L18)

## Possible Implementation
Maybe create a `kedro-datasets[light-spark]` that installs lightweight dependencies like `hdfs` and `s3fs` but not pyspark itself? 

## Possible Alternatives
I think probably the best way would be to completely redesign datasets to work with Databricks in a modern environment, supporting properly Unity Catalog tables, Unity Catalog authentication via external tables, `databricks-connect` for local development and other latest Databricks functionalities

I have seen [ManagedTableDataset](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/databricks/managed_table_dataset.py). Maybe building on top of this to support more Databricks stuff could be a good option

**Comment by noklam** [comment]
@MigQ2 Thanks for opening the issue as I was about to open it myself. I have encountered exactly the same problem. I think there are some problem in the dependencies and we should avoid `hdfs` (a rare dependency these days unless you run Spark on Hadoop). In any case it should be an optional one.

**Comment by MinuraPunchihewa** [comment]
@noklam I am happy to work on this with some guidance. 
As @MigQ2 mentioned, I think it makes sense to remove `spark-base,pandas-base,delta-base` from the dependencies for `databricks-managedtabledataset` and `databricks-externaltabledataset` [here](https://github.com/kedro-org/kedro-plugins/blob/b1bae8d370b20b1def75bc41a31733e43cb02f15/kedro-datasets/pyproject.toml#L40)? But, is there anything else we need to address?

**Comment by noklam** [comment]
I think the problem here is, the databricks dataset is importing spark dataset as a dependencies. So technically we cannot avoid this dependencies without first changing the source code for that class.

Just a quick reply on phone, I need to check that again when I have access to my laptop again.

**Comment by MinuraPunchihewa** [comment]
You are right; it imports the `_get_spark()` method from `kedro_datasets.spark.spark_dataset`. Would it make sense to separate out some of these common utility functions to another sub-package?

**Comment by noklam** [comment]
I think this is a relative small function and do not justify a separate
package for it.

Ideally, we could break that as a dependency free utilities (import it does
not import spark, lazy import when called and handle missing import
gracefully) .

If it's not possible, I would rather keep the code duplicated in its own
sub module.

**Comment by MinuraPunchihewa** [comment]
Agreed, but I noticed that there are few other functions defined in the module for the Spark dataset that could potentially be of use to other datasets as well, such as `_parse_glob_pattern`, `_split_filepath` and then a few other Databricks utilities. Oh, and what I meant is that we could just create a separate sub-package within kedro-datasets to house these functions, not for them to be distributed separately. Something like:
```
kedro_datasets/
│
├── utilities/
│   ├── __init__.py 
│   ├── spark_utilities.py 
│   ├── databricks_utilities.py  
```

I did not quite understand what you meant by 'dependency free utilities'.

**Comment by MinuraPunchihewa** [comment]
Got it. Thank you; that makes sense, Let me give this a shot.

**Comment by astrojuanlu** [comment]
> If working locally with Databricks, [databricks-connect](https://docs.databricks.com/en/dev-tools/databricks-connect/python/index.html) is probably preferred and also installing vanilla pyspark risks breaking it

We re-discovered this problem in #1100, let's continue the conversation in #135
