### ISSUE TITLE
Possibly invalid pandas extras metadata in `kedro-datasets`

### ISSUE THREAD

**Issue by mariusz89016** [kedro-org/kedro-plugins#863]
Hello 👋 

During requirements compilation (`pip-compile requirements.in`) I get a warning:
```
WARNING: kedro-datasets 4.1.0 does not provide the extra 'pandas-gbqtabledataset-pandas-genericdataset'
```

It works but in compiled `requirements.txt` there's:
```
#   scroll to the right =>                                                                                                                       \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
kedro-datasets[pandas,pandas-base,pandas-csvdataset,pandas-deltatabledataset,pandas-exceldataset,pandas-featherdataset,pandas-gbqquerydataset,pandas-gbqtabledataset-pandas-genericdataset,pandas-hdfdataset,pandas-jsondataset,pandas-parquetdataset,pandas-sqlquerydataset,pandas-sqltabledataset,pandas-xmldataset]==4.1.0
```

In `requirements.in` I have an entry:
```
kedro-datasets[pandas]==4.1.0
```

...aaaand I think that root cause of this is dot instead of comma here:
https://github.com/kedro-org/kedro-plugins/blob/kedro-datasets-4.1.0/kedro-datasets/pyproject.toml#L107

Thanks in advance ☺️

**Comment by noklam** [comment]
@mariusz89016 Thanks for opening your first issue in Kedro! You are absolutely right and this should be an easy fix, do you want to open a PR?

**Comment by mariusz89016** [comment]
Yeah, definitely ☺️ I'll prepare a PR in a moment!
