### ISSUE TITLE
Drop support for python 3.8

### ISSUE THREAD

**Issue by felixscherz** [kedro-org/kedro-plugins#872]
## Description
Kedro itself just dropped support for python 3.8 (https://github.com/kedro-org/kedro/pull/4212) as it has reached EOL since 2024-10-07 (https://devguide.python.org/versions/). This is breaking a couple of CI jobs that install kedro from HEAD, affecting kedro-airflow, kedro-docker and kedro-telemetry.

Example CI failure: https://github.com/kedro-org/kedro-plugins/actions/runs/11235726053/job/31234293125?pr=870#step:8:3

## Context
Since python 3.8 has reached EOL and was dropped by kedro itself, it should probably be dropped by the corresponding plugins as well.

## Possible Implementation
I would be happy to submit a PR similar to #870 which removes python 3.8 from CI and updates the syntax where necessary.

**Comment by noklam** [comment]
@felixscherz Free feel to go ahead and do so. Please drop one plugin at a time instead of dropping all plugins at the same time. kedro-datasets have dropped 3.8 for a while, so I think it's just kedro-docker, kedro-airflow and kedro-telemetry.

**Comment by felixscherz** [comment]
Hi, I created the respective PRs. However, none of the CI will succeed since I only updated a single plugin per PR, meaning the other two still create CI failures when run.

**Comment by ankatiyar** [comment]
Yeah, I think it might need to be done all together @felixscherz @noklam

**Comment by felixscherz** [comment]
I worked around it by removing Python 3.8 from github actions for all the plugins in each PR, the one CI issue left now is one regarding the docs for kedro-datasets where a link to the matplotlib documentation returns 403, could this be due to too many requests during CI runs? The link works fine from my browser. See: https://github.com/kedro-org/kedro-plugins/actions/runs/11268849549/job/31336335427

**Comment by ankatiyar** [comment]
i'll re-trigger the tests

**Comment by ankatiyar** [comment]
Completed by #876 #877 and #878
