### ISSUE TITLE
kedro-datasets: allow skipping Python 3.12 unit tests for SnowflakeTableDatasets

### ISSUE THREAD

**Issue by tdhooghe** [kedro-org/kedro-plugins#890]
## Description
Currently, installing testing requirements are failing for SnowflakeTableDatasets for Python 3.12, because it is not supported yet by the SnowparkAPI... Skipping Python 3.12 makes the tests succeed, as shown [here](https://github.com/kedro-org/kedro-plugins/actions/runs/11346139955)

## Context
I want to create a PR (#881) for SnowflakeTableDatasets, and the unit testing is failing.

## Possible Implementation
Update CI/CD in such a way that it can skip unit tests for Python 3.12

## Possible Alternatives
- Skipping unit tests for SnowflakeTablesets like was done in the past, because of poor previous compatibility of SnowparkAPI.
- Praying for Snowflake to finally update Snowpark to be compatible with Python 3.12.

**Comment by tdhooghe** [comment]
Currently, SnowflakeTableDatasets are not included in testing (see [here](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/tests/snowflake/conftest.py)). Happy to keep it this way and merge #881, while bumping the `snowflake-snowpark-python` version to 1.23. That would be already much better than the current implementation of SnowflakeTableDataset which is stuck at version 1.0.0 (that only supports the depreciated Python 3.8 version). What do you think of this?

**Comment by merelcht** [comment]
Hi @tdhooghe that sounds good to me. I was actually thinking we probably need to demote this dataset to experimental, since it doesn't technically adhere to our requirements of testing and python version support. 

Of course, if the testing framework you linked works fine, we can then make it a core dataset again.

**Comment by tdhooghe** [comment]
Hmm makes sense, although I think it would be really nice to have this one as core dataset.. If I implement the testing framework above, would the team then be fine of not having compatibility with Python 3.12 (for now, and once it is there, I will make the PR for including)?

**Comment by merelcht** [comment]
Done in #881
