### ISSUE TITLE
Switch to `uv` in `kedro-docker`

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-plugins#906]
## Description

https://github.com/kedro-org/kedro-plugins/blob/bc2ad07aa4d5dedb1d6874b1dae08df2e7b68521/kedro-docker/kedro_docker/template/Dockerfile.simple#L6-L7

Would be nice to use `uv` instead, which can be 10x or 100x faster.

Example: https://hynek.me/articles/docker-uv/

**Comment by MinuraPunchihewa** [comment]
Hey @astrojuanlu,
Can I take this up? Big fan of `uv`.

**Comment by MinuraPunchihewa** [comment]
@merelcht Can I open a PR for this?

**Comment by merelcht** [comment]
Yes go for it! @MinuraPunchihewa
